# Generated by Django 4.2.7 on 2024-02-02 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabañas', '0002_rename_tipo_cabaña_cabaña_tipocabaña_and_more'),
        ('reservas', '0004_alter_reserva_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservas_cabañas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('id_cabaña', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabañas.cabaña')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.reserva')),
            ],
        ),
    ]
