# Generated by Django 5.0 on 2024-02-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabañas', '0002_rename_tipo_cabaña_cabaña_tipocabaña_and_more'),
        ('reservas', '0006_remove_reserva_codigo_reserva_alter_reserva_estado'),
        ('reservas_cabañas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reservas_cabañas',
            new_name='Reserva_cabaña',
        ),
    ]
