# Generated by Django 4.2.7 on 2024-03-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_cabañas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas_cabañas',
            name='valor',
        ),
    ]
