# Generated by Django 4.2.7 on 2024-03-04 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_cabañas', '0002_rename_reservas_cabañas_reserva_cabaña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva_cabaña',
            old_name='valor',
            new_name='precio',
        ),
    ]
