# Generated by Django 4.2.7 on 2024-03-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_remove_reserva_codigo_reserva_alter_reserva_estado'),
        ('cabañas', '0002_rename_tipo_cabaña_cabaña_tipocabaña_and_more'),
        ('reservas_cabañas', '0002_remove_reservas_cabañas_valor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reservas_cabañas',
            new_name='Reserva_cabaña',
        ),
    ]
