# Generated by Django 4.2.7 on 2024-02-01 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=255)),
                ('metodo_pago', models.CharField(max_length=200)),
                ('valor', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.reserva')),
            ],
        ),
    ]
