# Generated by Django 4.2.7 on 2024-02-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_remove_pago_status_alter_pago_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
