# Generated by Django 4.2.7 on 2024-02-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_coder_alter_reserva_cliente_and_more'),
        ('pagos', '0003_pago_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(default='True'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(default='True', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='valor',
            field=models.IntegerField(default='True'),
        ),
    ]
