# Generated by Django 4.2.7 on 2024-02-01 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_coder_alter_reserva_cliente_and_more'),
        ('pagos', '0004_alter_pago_fecha_alter_pago_reserva_alter_pago_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
