# Generated by Django 4.2.7 on 2024-01-29 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipocabañas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocabaña',
            old_name='name',
            new_name='nombre',
        ),
    ]
