# Generated by Django 4.2.7 on 2024-03-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva_servicio',
            name='valor',
        ),
    ]
