# Generated by Django 4.2.7 on 2024-03-04 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva_servicio',
            old_name='valor',
            new_name='precio',
        ),
    ]
