# Generated by Django 4.2.7 on 2024-03-04 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_servicios', '0002_rename_valor_reserva_servicio_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva_servicio',
            old_name='precio',
            new_name='precio_S',
        ),
    ]
