# Generated by Django 4.2.7 on 2024-03-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_servicios', '0002_remove_reserva_servicio_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva_servicio',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
