# Generated by Django 5.0.1 on 2024-01-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='static/images_servicio')),
                ('status', models.BooleanField(default=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
