# Generated by Django 4.2.7 on 2024-01-30 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipocabañas', '0002_rename_name_tipocabaña_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField(max_length=10)),
                ('precio', models.IntegerField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.FileField(null=True, upload_to='static/images_cabaña')),
                ('status', models.BooleanField(default=True)),
                ('tipo_cabaña', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tipocabañas.tipocabaña')),
            ],
        ),
    ]
