# Generated by Django 4.2.7 on 2024-01-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabañas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabaña',
            old_name='tipo_cabaña',
            new_name='tipocabaña',
        ),
        migrations.AlterField(
            model_name='cabaña',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cabaña',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
