# Generated by Django 4.2.7 on 2024-02-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='coder',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_fin',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='valor',
            field=models.IntegerField(default=True),
        ),
    ]
