# Generated by Django 4.2.7 on 2024-02-02 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('reservas', '0003_alter_reserva_coder_alter_reserva_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente'),
        ),
    ]
