# Generated by Django 4.2.7 on 2024-03-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_remove_reserva_codigo_reserva_alter_reserva_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='valor',
            new_name='precio',
        ),
    ]
